details:
  namespace: student6-bookinfo-uat
  image: ghcr.io/korawit01/bookinfo-details
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
  healthCheckPath: "/health"
ingress:
  host: bookinfo.uat.opsta.net
  path: "/student6/details(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  